# Generated by Django 4.2.6 on 2023-10-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("links", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retail_network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=21,
                        null=True,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата регистрации звена продажи",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="links.link",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="products.product", verbose_name="Продукты"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail_network.retail_network",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети продажи",
                "verbose_name_plural": "звенья сети продаж",
            },
        ),
    ]
