# Generated by Django 4.2.6 on 2023-10-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retail_network",
            name="debt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=21,
                null=True,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
    ]
