# Generated by Django 4.2.6 on 2023-10-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("factory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название продукта"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата регистрации торара",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_product",
                        to="factory.factory",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
